imagesAll = [
    {imageUrl: './images/icon/museum.png', id: 'museum'},
    {imageUrl: './images/icon/church.png', id: 'church'},
    {imageUrl: './images/icon/shop.png', id: 'shop'},
    {imageUrl: './images/icon/nature.png', id: 'nature'},
    {imageUrl: './images/icon/theatre.png', id: 'theatre'},
    {imageUrl: './images/icon/harbor.png', id: 'harbor'},
    {imageUrl: './images/icon/indoor.png', id: 'indoor'},
    {imageUrl: './images/icon/building.png', id: 'building'},

    {imageUrl: './images/poiTest/Melbourne Aquarium.jpg', id: 'Melbourne Aquarium'},
    {imageUrl: './images/poiTest/The Museum Of Australian Chinese History.jpg', id: 'The Museum Of Australian Chinese History'},
    {imageUrl: './images/poiTest/Australian Centre For The Moving Image (ACMI).jpg', id: 'Australian Centre For The Moving Image (ACMI)'},
    {imageUrl: './images/poiTest/Cooks\' Cottage.jpg', id: 'Cooks\' Cottage'},
    {imageUrl: './images/poiTest/Koorie Heritage Trust Inc.jpg', id: 'Koorie Heritage Trust Inc'},
    {imageUrl: './images/poiTest/The Ian Potter Museum Of Art.jpg', id: 'The Ian Potter Museum Of Art'},
    {imageUrl: './images/poiTest/Fire Services Museum Victoria.jpg', id: 'Fire Services Museum Victoria'},
    {imageUrl: './images/poiTest/Immigration Museum.jpg', id: 'Immigration Museum'},
    {imageUrl: './images/poiTest/Victoria Police Museum.jpg', id: 'Victoria Police Museum'},
    {imageUrl: './images/poiTest/Sinclair\'s Cottage.jpg', id: 'Sinclair\'s Cottage'},
    {imageUrl: './images/poiTest/National Sports Museum.jpg', id: 'National Sports Museum'},
    {imageUrl: './images/poiTest/Melbourne Museum.jpg', id: 'Melbourne Museum'},
    {imageUrl: './images/poiTest/Fox Classic Car Collection.jpg', id: 'Fox Classic Car Collection'},
    {imageUrl: './images/poiTest/Thoroughbred Racing Gallery.jpg', id: 'Thoroughbred Racing Gallery'},
    {imageUrl: './images/poiTest/The Ian Potter Centre: NGV Australia.jpg', id: 'The Ian Potter Centre: NGV Australia'},
    {imageUrl: './images/poiTest/Victorian Arts Centre.jpg', id: 'Victorian Arts Centre'},
    {imageUrl: './images/poiTest/Australian Centre for Contemporary Art.jpg', id: 'Australian Centre for Contemporary Art'},
    {imageUrl: './images/poiTest/Polly Woodside.jpg', id: 'Polly Woodside'},
    {imageUrl: './images/poiTest/Old Melbourne Gaol Crime & Justice Experience.jpg', id: 'Old Melbourne Gaol Crime & Justice Experience'},
    {imageUrl: './images/poiTest/Webb Bridge.jpg', id: 'Webb Bridge'},
    {imageUrl: './images/poiTest/Crown Entertainment Complex.jpg', id: 'Crown Entertainment Complex'},
    {imageUrl: './images/poiTest/Melbourne General Cemetery.jpg', id: 'Melbourne General Cemetery'},
    {imageUrl: './images/poiTest/St Pauls Cathedral.jpg', id: 'St Pauls Cathedral'},
    {imageUrl: './images/poiTest/St Patricks Cathedral.jpg', id: 'St Patricks Cathedral'},
    {imageUrl: './images/poiTest/The Parish of Christ Church South Yarra.jpg', id: 'The Parish of Christ Church South Yarra'},
    {imageUrl: './images/poiTest/South Yarra Presbyterian Church.jpg', id: 'South Yarra Presbyterian Church'},
    {imageUrl: './images/poiTest/St Thomas Aquinas Church.jpg', id: 'St Thomas Aquinas Church'},
    {imageUrl: './images/poiTest/Collins Street Baptist Church.jpg', id: 'Collins Street Baptist Church'},
    {imageUrl: './images/poiTest/Holy Rosary.jpg', id: 'Holy Rosary'},
    {imageUrl: './images/poiTest/Christ Church Kensington.jpg', id: 'Christ Church Kensington'},
    {imageUrl: './images/poiTest/St Alban Anglican Church.jpg', id: 'St Alban Anglican Church'},
    {imageUrl: './images/poiTest/Ukranian Catholic Cathedral.jpg', id: 'Ukranian Catholic Cathedral'},
    {imageUrl: './images/poiTest/St Michaels.jpg', id: 'St Michaels'},
    {imageUrl: './images/poiTest/Our Lady of Lebanon Church.jpg', id: 'Our Lady of Lebanon Church'},
    {imageUrl: './images/poiTest/All Nations Uniting Church.jpg', id: 'All Nations Uniting Church'},
    {imageUrl: './images/poiTest/Melbourne Unitarian Church.jpg', id: 'Melbourne Unitarian Church'},
    {imageUrl: './images/poiTest/North Melbourne Uniting.jpg', id: 'North Melbourne Uniting'},
    {imageUrl: './images/poiTest/St Johns Lutheran Church.jpg', id: 'St Johns Lutheran Church'},
    {imageUrl: './images/poiTest/Holy Trinity.jpg', id: 'Holy Trinity'},
    {imageUrl: './images/poiTest/Lutheran Trinity Church.jpg', id: 'Lutheran Trinity Church'},
    {imageUrl: './images/poiTest/St Peter\'s Eastern Hill.jpg', id: 'St Peter\'s Eastern Hill'},
    {imageUrl: './images/poiTest/Greek Orthodox Church.jpg', id: 'Greek Orthodox Church'},
    {imageUrl: './images/poiTest/St Michael\'s Uniting Church.jpg', id: 'St Michael\'s Uniting Church'},
    {imageUrl: './images/poiTest/Scots Church.jpg', id: 'Scots Church'},
    {imageUrl: './images/poiTest/Church of Christ.jpg', id: 'Church of Christ'},
    {imageUrl: './images/poiTest/Welsh Presbyterian Church.jpg', id: 'Welsh Presbyterian Church'},
    {imageUrl: './images/poiTest/Romanian Orthodox.jpg', id: 'Romanian Orthodox'},
    {imageUrl: './images/poiTest/St Mary\'s Anglican Church.jpg', id: 'St Mary\'s Anglican Church'},
    {imageUrl: './images/poiTest/St James Church.jpg', id: 'St James Church'},
    {imageUrl: './images/poiTest/St Augustines Church.jpg', id: 'St Augustines Church'},
    {imageUrl: './images/poiTest/Wesley Church.jpg', id: 'Wesley Church'},
    {imageUrl: './images/poiTest/St Francis Church.jpg', id: 'St Francis Church'},
    {imageUrl: './images/poiTest/IMAX Melbourne.jpg', id: 'IMAX Melbourne'},
    {imageUrl: './images/poiTest/Harbour Town.jpg', id: 'Harbour Town'},
    {imageUrl: './images/poiTest/Railway Good Shed No 2.jpg', id: 'Railway Good Shed No 2'},
    {imageUrl: './images/poiTest/David Jones.jpg', id: 'David Jones'},
    {imageUrl: './images/poiTest/Myer.jpg', id: 'Myer'},
    {imageUrl: './images/poiTest/Bishopscourt.jpg', id: 'Bishopscourt'},
    {imageUrl: './images/poiTest/Government House.jpg', id: 'Government House'},
    {imageUrl: './images/poiTest/Channel 7 - Melbourne Broadcast Centre.jpg', id: 'Channel 7 - Melbourne Broadcast Centre'},
    {imageUrl: './images/poiTest/Central City Studios.jpg', id: 'Central City Studios'},
    {imageUrl: './images/poiTest/Metropolitan Fire Brigade (MFB).jpg', id: 'Metropolitan Fire Brigade (MFB)'},
    {imageUrl: './images/poiTest/Dallas Brooks Centre.jpg', id: 'Dallas Brooks Centre'},
    {imageUrl: './images/poiTest/Central Pier.jpg', id: 'Central Pier'},
    {imageUrl: './images/poiTest/Melbourne Convention Centre.jpg', id: 'Melbourne Convention Centre'},
    {imageUrl: './images/poiTest/Melbourne Exhibition Centre.jpg', id: 'Melbourne Exhibition Centre'},
    {imageUrl: './images/poiTest/Kangan Batman Tafe.jpg', id: 'Kangan Batman Tafe'},
    {imageUrl: './images/poiTest/Melbourne Magistrates Court.jpg', id: 'Melbourne Magistrates Court'},
    {imageUrl: './images/poiTest/North Melbourne Recreation Centre (Gymnasium).jpg', id: 'North Melbourne Recreation Centre (Gymnasium)'},
    {imageUrl: './images/poiTest/The Mission To Seafarers Victoria.jpg', id: 'The Mission To Seafarers Victoria'},
    {imageUrl: './images/poiTest/Carlton Baths.jpg', id: 'Carlton Baths'},
    {imageUrl: './images/poiTest/Icehouse.jpg', id: 'Icehouse'},
    {imageUrl: './images/poiTest/Artplay.jpg', id: 'Artplay'},
    {imageUrl: './images/poiTest/Kraft.jpg', id: 'Kraft'},
    {imageUrl: './images/poiTest/Lincoln Square.jpg', id: 'Lincoln Square'},
    {imageUrl: './images/poiTest/Sandridge Rail Bridge.jpg', id: 'Sandridge Rail Bridge'},
    {imageUrl: './images/poiTest/Westgate Park.jpg', id: 'Westgate Park'},
    {imageUrl: './images/poiTest/Murchinson Square.jpg', id: 'Murchinson Square'},
    {imageUrl: './images/poiTest/Macarthur Square.jpg', id: 'Macarthur Square'},
    {imageUrl: './images/poiTest/Piazza Italia.jpg', id: 'Piazza Italia'},
    {imageUrl: './images/poiTest/Argyle Square.jpg', id: 'Argyle Square'},
    {imageUrl: './images/poiTest/Fitzroy Gardens.jpg', id: 'Fitzroy Gardens'},
    {imageUrl: './images/poiTest/Fawkner Park.jpg', id: 'Fawkner Park'},
    {imageUrl: './images/poiTest/Flagstaff Gardens.jpg', id: 'Flagstaff Gardens'},
    {imageUrl: './images/poiTest/Royal Botanic Gardens.jpg', id: 'Royal Botanic Gardens'},
    {imageUrl: './images/poiTest/Shrine of Rembrance Reserve.jpg', id: 'Shrine of Rembrance Reserve'},
    {imageUrl: './images/poiTest/Princes Park.jpg', id: 'Princes Park'},
    {imageUrl: './images/poiTest/Royal Park.jpg', id: 'Royal Park'},
    {imageUrl: './images/poiTest/J.J Holland Park.jpg', id: 'J.J Holland Park'},
    {imageUrl: './images/poiTest/North Melbourne Recreation Reserve.jpg', id: 'North Melbourne Recreation Reserve'},
    {imageUrl: './images/poiTest/Alexandra Gardens.jpg', id: 'Alexandra Gardens'},
    {imageUrl: './images/poiTest/Riverslide Skate Park.jpg', id: 'Riverslide Skate Park'},
    {imageUrl: './images/poiTest/Newmarket Reserve.jpg', id: 'Newmarket Reserve'},
    {imageUrl: './images/poiTest/Point Park.jpg', id: 'Point Park'},
    {imageUrl: './images/poiTest/Docklands Park.jpg', id: 'Docklands Park'},
    {imageUrl: './images/poiTest/New Quay.jpg', id: 'New Quay'},
    {imageUrl: './images/poiTest/Federation Square.jpg', id: 'Federation Square'},
    {imageUrl: './images/poiTest/Queen Victoria Gardens.jpg', id: 'Queen Victoria Gardens'},
    {imageUrl: './images/poiTest/Richmond Football Club.jpg', id: 'Richmond Football Club'},
    {imageUrl: './images/poiTest/Batman Park.jpg', id: 'Batman Park'},
    {imageUrl: './images/poiTest/Treasury Gardens.jpg', id: 'Treasury Gardens'},
    {imageUrl: './images/poiTest/Kings Domain.jpg', id: 'Kings Domain'},
    {imageUrl: './images/poiTest/Carlton Gardens North.jpg', id: 'Carlton Gardens North'},
    {imageUrl: './images/poiTest/Powlett Reserve.jpg', id: 'Powlett Reserve'},
    {imageUrl: './images/poiTest/Carlton Gardens South.jpg', id: 'Carlton Gardens South'},
    {imageUrl: './images/poiTest/The Melbourne Athenaeum Library.jpg', id: 'The Melbourne Athenaeum Library'},
    {imageUrl: './images/poiTest/Etihad Stadium.jpg', id: 'Etihad Stadium'},
    {imageUrl: './images/poiTest/Westpac Centre.jpg', id: 'Westpac Centre'},
    {imageUrl: './images/poiTest/City Baths.jpg', id: 'City Baths'},
    {imageUrl: './images/poiTest/North Melbourne Recreation Centre (Aquatic).jpg', id: 'North Melbourne Recreation Centre (Aquatic)'},
    {imageUrl: './images/poiTest/Margaret Court Arena.jpg', id: 'Margaret Court Arena'},
    {imageUrl: './images/poiTest/Melbourne Park.jpg', id: 'Melbourne Park'},
    {imageUrl: './images/poiTest/Rod Laver Arena.jpg', id: 'Rod Laver Arena'},
    {imageUrl: './images/poiTest/AAMI Park.jpg', id: 'AAMI Park'},
    {imageUrl: './images/poiTest/Melbourne Cricket Ground (MCG).jpg', id: 'Melbourne Cricket Ground (MCG)'},
    {imageUrl: './images/poiTest/Flemington Racecourse.jpg', id: 'Flemington Racecourse'},
    {imageUrl: './images/poiTest/Visy Park.jpg', id: 'Visy Park'},
    {imageUrl: './images/poiTest/Carlton Football Club.jpg', id: 'Carlton Football Club'},
    {imageUrl: './images/poiTest/State Netball Hockey Centre.jpg', id: 'State Netball Hockey Centre'},
    {imageUrl: './images/poiTest/New Quay Marina.jpg', id: 'New Quay Marina'},
    {imageUrl: './images/poiTest/Eureka Skydeck 88.jpg', id: 'Eureka Skydeck 88'},
    {imageUrl: './images/poiTest/Melbourne Star Observation Wheel.jpg', id: 'Melbourne Star Observation Wheel'},
    {imageUrl: './images/poiTest/State Coroners Office.jpg', id: 'State Coroners Office'},
    {imageUrl: './images/poiTest/Donor Tissue Bank of Victoria.jpg', id: 'Donor Tissue Bank of Victoria'},
    {imageUrl: './images/poiTest/Victorian Insitute of Forensic Medicine.jpg', id: 'Victorian Insitute of Forensic Medicine'},
    {imageUrl: './images/poiTest/Coronial Services Centre of Victoria.jpg', id: 'Coronial Services Centre of Victoria'},
    {imageUrl: './images/poiTest/SBS (Special Broadcasting Service).jpg', id: 'SBS (Special Broadcasting Service)'},
    {imageUrl: './images/poiTest/Former Royal Mint.jpg', id: 'Former Royal Mint'},
    {imageUrl: './images/poiTest/Parliament House.jpg', id: 'Parliament House'},
    {imageUrl: './images/poiTest/Australian Red Cross.jpg', id: 'Australian Red Cross'},
    {imageUrl: './images/poiTest/Old Treasury Building.jpg', id: 'Old Treasury Building'},
    {imageUrl: './images/poiTest/Melbourne Showgrounds.jpg', id: 'Melbourne Showgrounds'},
    {imageUrl: './images/poiTest/Riverside Park.jpg', id: 'Riverside Park'},
    {imageUrl: './images/poiTest/Wonderland Park.jpg', id: 'Wonderland Park'},
    {imageUrl: './images/poiTest/Melbourne Zoo.jpg', id: 'Melbourne Zoo'},
    {imageUrl: './images/poiTest/Victoria Police.jpg', id: 'Victoria Police'},
    {imageUrl: './images/poiTest/North Melbourne Primary School.jpg', id: 'North Melbourne Primary School'},
    {imageUrl: './images/poiTest/Kensington Primary School.jpg', id: 'Kensington Primary School'},
    {imageUrl: './images/poiTest/Carlton Primary School.jpg', id: 'Carlton Primary School'},
    {imageUrl: './images/poiTest/Carlton Gardens Primary School.jpg', id: 'Carlton Gardens Primary School'},
    {imageUrl: './images/poiTest/Epworth Freemasons Hospital.jpg', id: 'Epworth Freemasons Hospital'},
    {imageUrl: './images/poiTest/Epworth Freemasons Hospital : Medical Centre.jpg', id: 'Epworth Freemasons Hospital : Medical Centre'},
    {imageUrl: './images/poiTest/Melbourne Private Hospital.jpg', id: 'Melbourne Private Hospital'},
    {imageUrl: './images/poiTest/Melbourne International Shooting Club.jpg', id: 'Melbourne International Shooting Club'},
    {imageUrl: './images/poiTest/Royal Park Golf Course.jpg', id: 'Royal Park Golf Course'},
    {imageUrl: './images/poiTest/County Court Melbourne.jpg', id: 'County Court Melbourne'},
    {imageUrl: './images/poiTest/Melbourne Childrens Court.jpg', id: 'Melbourne Childrens Court'},
    {imageUrl: './images/poiTest/Conservatory.jpg', id: 'Conservatory'},
    {imageUrl: './images/poiTest/Commonwealth Law Courts.jpg', id: 'Commonwealth Law Courts'},
    {imageUrl: './images/poiTest/Shrine of Remembrance.jpg', id: 'Shrine of Remembrance'},
    {imageUrl: './images/poiTest/NGV International.jpg', id: 'NGV International'},
    {imageUrl: './images/poiTest/Melbourne Recital Centre.jpg', id: 'Melbourne Recital Centre'},
    {imageUrl: './images/poiTest/Elisabeth Murdoch Hall.jpg', id: 'Elisabeth Murdoch Hall'},
    {imageUrl: './images/poiTest/Sidney Myer Music Bowl.jpg', id: 'Sidney Myer Music Bowl'},
    {imageUrl: './images/poiTest/Melbourne Town Hall.jpg', id: 'Melbourne Town Hall'},
    {imageUrl: './images/poiTest/Supreme Court.jpg', id: 'Supreme Court'},
    {imageUrl: './images/poiTest/State Library Victoria.jpg', id: 'State Library Victoria'},
    {imageUrl: './images/poiTest/Royal Dental Hospital.jpg', id: 'Royal Dental Hospital'},
    {imageUrl: './images/poiTest/Peter Maccallum Cancer Institute.jpg', id: 'Peter Maccallum Cancer Institute'},
    {imageUrl: './images/poiTest/Royal Melbourne Hospital.jpg', id: 'Royal Melbourne Hospital'},
    {imageUrl: './images/poiTest/Alfred Hospital.jpg', id: 'Alfred Hospital'},
    {imageUrl: './images/poiTest/Royal Childrens Hospital.jpg', id: 'Royal Childrens Hospital'},
    {imageUrl: './images/poiTest/Royal Womens Hospital.jpg', id: 'Royal Womens Hospital'},
    {imageUrl: './images/poiTest/The Royal Victorian Eye & Ear Hospital.jpg', id: 'The Royal Victorian Eye & Ear Hospital'},
    {imageUrl: './images/poiTest/North Melbourne Railway Station.jpg', id: 'North Melbourne Railway Station'},
    {imageUrl: './images/poiTest/Melbourne Central Railway Station.jpg', id: 'Melbourne Central Railway Station'},
    {imageUrl: './images/poiTest/Flinders Street Railway Station.jpg', id: 'Flinders Street Railway Station'},
    {imageUrl: './images/poiTest/Newmarket Railway Station.jpg', id: 'Newmarket Railway Station'},
    {imageUrl: './images/poiTest/Showgrounds Railway Station (Flemington).jpg', id: 'Showgrounds Railway Station (Flemington)'},
    {imageUrl: './images/poiTest/Flemington Racecourse Railway Station.jpg', id: 'Flemington Racecourse Railway Station'},
    {imageUrl: './images/poiTest/Flagstaff Railway Station.jpg', id: 'Flagstaff Railway Station'},
    {imageUrl: './images/poiTest/Parliament Railway Station.jpg', id: 'Parliament Railway Station'},
    {imageUrl: './images/poiTest/Royal Park Railway Station.jpg', id: 'Royal Park Railway Station'},
    {imageUrl: './images/poiTest/South Kensington Railway Station.jpg', id: 'South Kensington Railway Station'},
    {imageUrl: './images/poiTest/Kensington Railway Station.jpg', id: 'Kensington Railway Station'},
    {imageUrl: './images/poiTest/Jolimont-MCG Railway Station (East Melbourne) - Train stop.jpg', id: 'Jolimont-MCG Railway Station (East Melbourne) - Train stop'},
    {imageUrl: './images/poiTest/Richmond Railway Station (Richmond) - Train stop.jpg', id: 'Richmond Railway Station (Richmond) - Train stop'},
    {imageUrl: './images/poiTest/Southern Cross Railway Station.jpg', id: 'Southern Cross Railway Station'},
    {imageUrl: './images/poiTest/Flemington Bridge Railway Station.jpg', id: 'Flemington Bridge Railway Station'},
    {imageUrl: './images/poiTest/Queen Victoria Market.jpg', id: 'Queen Victoria Market'},
    {imageUrl: './images/poiTest/Treasury Reserve.jpg', id: 'Treasury Reserve'},
    {imageUrl: './images/poiTest/ANZ \'Gothic\' Bank.jpg', id: 'ANZ \'Gothic\' Bank'},
    {imageUrl: './images/poiTest/Melbourne Central.jpg', id: 'Melbourne Central'},
    {imageUrl: './images/poiTest/Southgate Arts and Leisure Precinct.jpg', id: 'Southgate Arts and Leisure Precinct'},
    {imageUrl: './images/poiTest/Council House 2 (CH2).jpg', id: 'Council House 2 (CH2)'},
    {imageUrl: './images/poiTest/Freshwater Place.jpg', id: 'Freshwater Place'},
    {imageUrl: './images/poiTest/QV Village.jpg', id: 'QV Village'},
    {imageUrl: './images/poiTest/Eureka Tower.jpg', id: 'Eureka Tower'},
    {imageUrl: './images/poiTest/Melbourne Girls Grammar School.jpg', id: 'Melbourne Girls Grammar School'},
    {imageUrl: './images/poiTest/Wesley College.jpg', id: 'Wesley College'},
    {imageUrl: './images/poiTest/University High School.jpg', id: 'University High School'},
    {imageUrl: './images/poiTest/Melbourne Grammar School.jpg', id: 'Melbourne Grammar School'},
    {imageUrl: './images/poiTest/Melbourne Wholesale Fish Market.jpg', id: 'Melbourne Wholesale Fish Market'},
    {imageUrl: './images/poiTest/East Melbourne Synagogue.jpg', id: 'East Melbourne Synagogue'},
    {imageUrl: './images/poiTest/RMIT University.jpg', id: 'RMIT University'},
    {imageUrl: './images/poiTest/University of Melbourne.jpg', id: 'University of Melbourne'},
    {imageUrl: './images/poiTest/BIO 21 Institute.jpg', id: 'BIO 21 Institute'},
    {imageUrl: './images/poiTest/University of Melbourne (VCA and Music).jpg', id: 'University of Melbourne (VCA and Music)'},
    {imageUrl: './images/poiTest/La Mama Theatre.jpg', id: 'La Mama Theatre'},
    {imageUrl: './images/poiTest/Comedy Theatre.jpg', id: 'Comedy Theatre'},
    {imageUrl: './images/poiTest/Her Majesty\'s Theatre.jpg', id: 'Her Majesty\'s Theatre'},
    {imageUrl: './images/poiTest/Carlton Courthouse Theatre.jpg', id: 'Carlton Courthouse Theatre'},
    {imageUrl: './images/poiTest/Athanaeum Theatre.jpg', id: 'Athanaeum Theatre'},
    {imageUrl: './images/poiTest/Hamer Hall.jpg', id: 'Hamer Hall'},
    {imageUrl: './images/poiTest/MTC Theatre.jpg', id: 'MTC Theatre'},
    {imageUrl: './images/poiTest/Malthouse Theatre.jpg', id: 'Malthouse Theatre'},
    {imageUrl: './images/poiTest/Regent Theatre.jpg', id: 'Regent Theatre'},
    {imageUrl: './images/poiTest/Princess Theatre.jpg', id: 'Princess Theatre'},
    {imageUrl: './images/poiTest/St Martins Youth Arts Centre.jpg', id: 'St Martins Youth Arts Centre'},
    {imageUrl: './images/poiTest/State Theatre.jpg', id: 'State Theatre'},
    {imageUrl: './images/poiTest/Playhouse.jpg', id: 'Playhouse'},
    {imageUrl: './images/poiTest/FairFax Studio.jpg', id: 'FairFax Studio'},
    {imageUrl: './images/poiTest/Port of Melbourne.jpg', id: 'Port of Melbourne'},
    {imageUrl: './images/poiTest/Melbourne International Karting Complex.jpg', id: 'Melbourne International Karting Complex'},
    {imageUrl: './images/poiTest/Melbourne Visitor Centre.jpg', id: 'Melbourne Visitor Centre'},
    {imageUrl: './images/poiTest/Melbourne Visitor Booth.jpg', id: 'Melbourne Visitor Booth'},
]