imagesAll = [
    {imageUrl: './images/icon/museum.png', id: 'museum'},
    {imageUrl: './images/icon/church.png', id: 'church'},
    {imageUrl: './images/icon/shop.png', id: 'shop'},
    {imageUrl: './images/icon/nature.png', id: 'nature'},
    {imageUrl: './images/icon/theatre.png', id: 'theatre'},
    {imageUrl: './images/icon/harbor.png', id: 'harbor'},
    {imageUrl: './images/icon/indoor.png', id: 'indoor'},
    {imageUrl: './images/icon/building.png', id: 'building'},
    {imageUrl: './images/icon/sport.png', id: 'sport'},

    {imageUrl: './images/poiTest/icons/Melbourne Aquarium.png', id: 'Melbourne Aquarium'},
    {imageUrl: './images/poiTest/icons/The Museum Of Australian Chinese History.png', id: 'The Museum Of Australian Chinese History'},
    {imageUrl: './images/poiTest/icons/Australian Centre For The Moving Image (ACMI).png', id: 'Australian Centre For The Moving Image (ACMI)'},
    {imageUrl: './images/poiTest/icons/Cooks\' Cottage.png', id: 'Cooks\' Cottage'},
    {imageUrl: './images/poiTest/icons/Koorie Heritage Trust Inc.png', id: 'Koorie Heritage Trust Inc'},
    {imageUrl: './images/poiTest/icons/The Ian Potter Museum Of Art.png', id: 'The Ian Potter Museum Of Art'},
    {imageUrl: './images/poiTest/icons/Fire Services Museum Victoria.png', id: 'Fire Services Museum Victoria'},
    {imageUrl: './images/poiTest/icons/Immigration Museum.png', id: 'Immigration Museum'},
    {imageUrl: './images/poiTest/icons/Victoria Police Museum.png', id: 'Victoria Police Museum'},
    {imageUrl: './images/poiTest/icons/Sinclair\'s Cottage.png', id: 'Sinclair\'s Cottage'},
    {imageUrl: './images/poiTest/icons/National Sports Museum.png', id: 'National Sports Museum'},
    {imageUrl: './images/poiTest/icons/Melbourne Museum.png', id: 'Melbourne Museum'},
    {imageUrl: './images/poiTest/icons/Fox Classic Car Collection.png', id: 'Fox Classic Car Collection'},
    {imageUrl: './images/poiTest/icons/Thoroughbred Racing Gallery.png', id: 'Thoroughbred Racing Gallery'},
    {imageUrl: './images/poiTest/icons/The Ian Potter Centre: NGV Australia.png', id: 'The Ian Potter Centre: NGV Australia'},
    {imageUrl: './images/poiTest/icons/Victorian Arts Centre.png', id: 'Victorian Arts Centre'},
    {imageUrl: './images/poiTest/icons/Australian Centre for Contemporary Art.png', id: 'Australian Centre for Contemporary Art'},
    {imageUrl: './images/poiTest/icons/Polly Woodside.png', id: 'Polly Woodside'},
    {imageUrl: './images/poiTest/icons/Old Melbourne Gaol Crime & Justice Experience.png', id: 'Old Melbourne Gaol Crime & Justice Experience'},
    {imageUrl: './images/poiTest/icons/Webb Bridge.png', id: 'Webb Bridge'},
    {imageUrl: './images/poiTest/icons/Crown Entertainment Complex.png', id: 'Crown Entertainment Complex'},
    {imageUrl: './images/poiTest/icons/Melbourne General Cemetery.png', id: 'Melbourne General Cemetery'},
    {imageUrl: './images/poiTest/icons/St Pauls Cathedral.png', id: 'St Pauls Cathedral'},
    {imageUrl: './images/poiTest/icons/St Patricks Cathedral.png', id: 'St Patricks Cathedral'},
    {imageUrl: './images/poiTest/icons/The Parish of Christ Church South Yarra.png', id: 'The Parish of Christ Church South Yarra'},
    {imageUrl: './images/poiTest/icons/South Yarra Presbyterian Church.png', id: 'South Yarra Presbyterian Church'},
    {imageUrl: './images/poiTest/icons/St Thomas Aquinas Church.png', id: 'St Thomas Aquinas Church'},
    {imageUrl: './images/poiTest/icons/Collins Street Baptist Church.png', id: 'Collins Street Baptist Church'},
    {imageUrl: './images/poiTest/icons/Holy Rosary.png', id: 'Holy Rosary'},
    {imageUrl: './images/poiTest/icons/Christ Church Kensington.png', id: 'Christ Church Kensington'},
    {imageUrl: './images/poiTest/icons/St Alban Anglican Church.png', id: 'St Alban Anglican Church'},
    {imageUrl: './images/poiTest/icons/Ukranian Catholic Cathedral.png', id: 'Ukranian Catholic Cathedral'},
    {imageUrl: './images/poiTest/icons/St Michaels.png', id: 'St Michaels'},
    {imageUrl: './images/poiTest/icons/Our Lady of Lebanon Church.png', id: 'Our Lady of Lebanon Church'},
    {imageUrl: './images/poiTest/icons/All Nations Uniting Church.png', id: 'All Nations Uniting Church'},
    {imageUrl: './images/poiTest/icons/Melbourne Unitarian Church.png', id: 'Melbourne Unitarian Church'},
    {imageUrl: './images/poiTest/icons/North Melbourne Uniting.png', id: 'North Melbourne Uniting'},
    {imageUrl: './images/poiTest/icons/St Johns Lutheran Church.png', id: 'St Johns Lutheran Church'},
    {imageUrl: './images/poiTest/icons/Holy Trinity.png', id: 'Holy Trinity'},
    {imageUrl: './images/poiTest/icons/Lutheran Trinity Church.png', id: 'Lutheran Trinity Church'},
    {imageUrl: './images/poiTest/icons/St Peter\'s Eastern Hill.png', id: 'St Peter\'s Eastern Hill'},
    {imageUrl: './images/poiTest/icons/Greek Orthodox Church.png', id: 'Greek Orthodox Church'},
    {imageUrl: './images/poiTest/icons/St Michael\'s Uniting Church.png', id: 'St Michael\'s Uniting Church'},
    {imageUrl: './images/poiTest/icons/Scots Church.png', id: 'Scots Church'},
    {imageUrl: './images/poiTest/icons/Church of Christ.png', id: 'Church of Christ'},
    {imageUrl: './images/poiTest/icons/Welsh Presbyterian Church.png', id: 'Welsh Presbyterian Church'},
    {imageUrl: './images/poiTest/icons/Romanian Orthodox.png', id: 'Romanian Orthodox'},
    {imageUrl: './images/poiTest/icons/St Mary\'s Anglican Church.png', id: 'St Mary\'s Anglican Church'},
    {imageUrl: './images/poiTest/icons/St James Church.png', id: 'St James Church'},
    {imageUrl: './images/poiTest/icons/St Augustines Church.png', id: 'St Augustines Church'},
    {imageUrl: './images/poiTest/icons/Wesley Church.png', id: 'Wesley Church'},
    {imageUrl: './images/poiTest/icons/St Francis Church.png', id: 'St Francis Church'},
    {imageUrl: './images/poiTest/icons/IMAX Melbourne.png', id: 'IMAX Melbourne'},
    {imageUrl: './images/poiTest/icons/Harbour Town.png', id: 'Harbour Town'},
    {imageUrl: './images/poiTest/icons/Railway Good Shed No 2.png', id: 'Railway Good Shed No 2'},
    {imageUrl: './images/poiTest/icons/David Jones.png', id: 'David Jones'},
    {imageUrl: './images/poiTest/icons/Myer.png', id: 'Myer'},
    {imageUrl: './images/poiTest/icons/Bishopscourt.png', id: 'Bishopscourt'},
    {imageUrl: './images/poiTest/icons/Government House.png', id: 'Government House'},
    {imageUrl: './images/poiTest/icons/Channel 7 - Melbourne Broadcast Centre.png', id: 'Channel 7 - Melbourne Broadcast Centre'},
    {imageUrl: './images/poiTest/icons/Central City Studios.png', id: 'Central City Studios'},
    {imageUrl: './images/poiTest/icons/Metropolitan Fire Brigade (MFB).png', id: 'Metropolitan Fire Brigade (MFB)'},
    {imageUrl: './images/poiTest/icons/Dallas Brooks Centre.png', id: 'Dallas Brooks Centre'},
    {imageUrl: './images/poiTest/icons/Central Pier.png', id: 'Central Pier'},
    {imageUrl: './images/poiTest/icons/Melbourne Convention Centre.png', id: 'Melbourne Convention Centre'},
    {imageUrl: './images/poiTest/icons/Melbourne Exhibition Centre.png', id: 'Melbourne Exhibition Centre'},
    {imageUrl: './images/poiTest/icons/Kangan Batman Tafe.png', id: 'Kangan Batman Tafe'},
    {imageUrl: './images/poiTest/icons/Melbourne Magistrates Court.png', id: 'Melbourne Magistrates Court'},
    {imageUrl: './images/poiTest/icons/North Melbourne Recreation Centre (Gymnasium).png', id: 'North Melbourne Recreation Centre (Gymnasium)'},
    {imageUrl: './images/poiTest/icons/The Mission To Seafarers Victoria.png', id: 'The Mission To Seafarers Victoria'},
    {imageUrl: './images/poiTest/icons/Carlton Baths.png', id: 'Carlton Baths'},
    {imageUrl: './images/poiTest/icons/Icehouse.png', id: 'Icehouse'},
    {imageUrl: './images/poiTest/icons/Artplay.png', id: 'Artplay'},
    {imageUrl: './images/poiTest/icons/Kraft.png', id: 'Kraft'},
    {imageUrl: './images/poiTest/icons/Lincoln Square.png', id: 'Lincoln Square'},
    {imageUrl: './images/poiTest/icons/Sandridge Rail Bridge.png', id: 'Sandridge Rail Bridge'},
    {imageUrl: './images/poiTest/icons/Westgate Park.png', id: 'Westgate Park'},
    {imageUrl: './images/poiTest/icons/Murchinson Square.png', id: 'Murchinson Square'},
    {imageUrl: './images/poiTest/icons/Macarthur Square.png', id: 'Macarthur Square'},
    {imageUrl: './images/poiTest/icons/Piazza Italia.png', id: 'Piazza Italia'},
    {imageUrl: './images/poiTest/icons/Argyle Square.png', id: 'Argyle Square'},
    {imageUrl: './images/poiTest/icons/Fitzroy Gardens.png', id: 'Fitzroy Gardens'},
    {imageUrl: './images/poiTest/icons/Fawkner Park.png', id: 'Fawkner Park'},
    {imageUrl: './images/poiTest/icons/Flagstaff Gardens.png', id: 'Flagstaff Gardens'},
    {imageUrl: './images/poiTest/icons/Royal Botanic Gardens.png', id: 'Royal Botanic Gardens'},
    {imageUrl: './images/poiTest/icons/Shrine of Rembrance Reserve.png', id: 'Shrine of Rembrance Reserve'},
    {imageUrl: './images/poiTest/icons/Princes Park.png', id: 'Princes Park'},
    {imageUrl: './images/poiTest/icons/Royal Park.png', id: 'Royal Park'},
    {imageUrl: './images/poiTest/icons/J.J Holland Park.png', id: 'J.J Holland Park'},
    {imageUrl: './images/poiTest/icons/North Melbourne Recreation Reserve.png', id: 'North Melbourne Recreation Reserve'},
    {imageUrl: './images/poiTest/icons/Alexandra Gardens.png', id: 'Alexandra Gardens'},
    {imageUrl: './images/poiTest/icons/Riverslide Skate Park.png', id: 'Riverslide Skate Park'},
    {imageUrl: './images/poiTest/icons/Newmarket Reserve.png', id: 'Newmarket Reserve'},
    {imageUrl: './images/poiTest/icons/Point Park.png', id: 'Point Park'},
    {imageUrl: './images/poiTest/icons/Docklands Park.png', id: 'Docklands Park'},
    {imageUrl: './images/poiTest/icons/New Quay.png', id: 'New Quay'},
    {imageUrl: './images/poiTest/icons/Federation Square.png', id: 'Federation Square'},
    {imageUrl: './images/poiTest/icons/Queen Victoria Gardens.png', id: 'Queen Victoria Gardens'},
    {imageUrl: './images/poiTest/icons/Richmond Football Club.png', id: 'Richmond Football Club'},
    {imageUrl: './images/poiTest/icons/Batman Park.png', id: 'Batman Park'},
    {imageUrl: './images/poiTest/icons/Treasury Gardens.png', id: 'Treasury Gardens'},
    {imageUrl: './images/poiTest/icons/Kings Domain.png', id: 'Kings Domain'},
    {imageUrl: './images/poiTest/icons/Carlton Gardens North.png', id: 'Carlton Gardens North'},
    {imageUrl: './images/poiTest/icons/Powlett Reserve.png', id: 'Powlett Reserve'},
    {imageUrl: './images/poiTest/icons/Carlton Gardens South.png', id: 'Carlton Gardens South'},
    {imageUrl: './images/poiTest/icons/The Melbourne Athenaeum Library.png', id: 'The Melbourne Athenaeum Library'},
    {imageUrl: './images/poiTest/icons/Etihad Stadium.png', id: 'Etihad Stadium'},
    {imageUrl: './images/poiTest/icons/Westpac Centre.png', id: 'Westpac Centre'},
    {imageUrl: './images/poiTest/icons/City Baths.png', id: 'City Baths'},
    {imageUrl: './images/poiTest/icons/North Melbourne Recreation Centre (Aquatic).png', id: 'North Melbourne Recreation Centre (Aquatic)'},
    {imageUrl: './images/poiTest/icons/Margaret Court Arena.png', id: 'Margaret Court Arena'},
    {imageUrl: './images/poiTest/icons/Melbourne Park.png', id: 'Melbourne Park'},
    {imageUrl: './images/poiTest/icons/Rod Laver Arena.png', id: 'Rod Laver Arena'},
    {imageUrl: './images/poiTest/icons/AAMI Park.png', id: 'AAMI Park'},
    {imageUrl: './images/poiTest/icons/Melbourne Cricket Ground (MCG).png', id: 'Melbourne Cricket Ground (MCG)'},
    {imageUrl: './images/poiTest/icons/Flemington Racecourse.png', id: 'Flemington Racecourse'},
    {imageUrl: './images/poiTest/icons/Visy Park.png', id: 'Visy Park'},
    {imageUrl: './images/poiTest/icons/Carlton Football Club.png', id: 'Carlton Football Club'},
    {imageUrl: './images/poiTest/icons/State Netball Hockey Centre.png', id: 'State Netball Hockey Centre'},
    {imageUrl: './images/poiTest/icons/New Quay Marina.png', id: 'New Quay Marina'},
    {imageUrl: './images/poiTest/icons/Eureka Skydeck 88.png', id: 'Eureka Skydeck 88'},
    {imageUrl: './images/poiTest/icons/Melbourne Star Observation Wheel.png', id: 'Melbourne Star Observation Wheel'},
    {imageUrl: './images/poiTest/icons/State Coroners Office.png', id: 'State Coroners Office'},
    {imageUrl: './images/poiTest/icons/Donor Tissue Bank of Victoria.png', id: 'Donor Tissue Bank of Victoria'},
    {imageUrl: './images/poiTest/icons/Victorian Insitute of Forensic Medicine.png', id: 'Victorian Insitute of Forensic Medicine'},
    {imageUrl: './images/poiTest/icons/Coronial Services Centre of Victoria.png', id: 'Coronial Services Centre of Victoria'},
    {imageUrl: './images/poiTest/icons/SBS (Special Broadcasting Service).png', id: 'SBS (Special Broadcasting Service)'},
    {imageUrl: './images/poiTest/icons/Former Royal Mint.png', id: 'Former Royal Mint'},
    {imageUrl: './images/poiTest/icons/Parliament House.png', id: 'Parliament House'},
    {imageUrl: './images/poiTest/icons/Australian Red Cross.png', id: 'Australian Red Cross'},
    {imageUrl: './images/poiTest/icons/Old Treasury Building.png', id: 'Old Treasury Building'},
    {imageUrl: './images/poiTest/icons/Melbourne Showgrounds.png', id: 'Melbourne Showgrounds'},
    {imageUrl: './images/poiTest/icons/Riverside Park.png', id: 'Riverside Park'},
    {imageUrl: './images/poiTest/icons/Wonderland Park.png', id: 'Wonderland Park'},
    {imageUrl: './images/poiTest/icons/Melbourne Zoo.png', id: 'Melbourne Zoo'},
    {imageUrl: './images/poiTest/icons/Victoria Police.png', id: 'Victoria Police'},
    {imageUrl: './images/poiTest/icons/North Melbourne Primary School.png', id: 'North Melbourne Primary School'},
    {imageUrl: './images/poiTest/icons/Kensington Primary School.png', id: 'Kensington Primary School'},
    {imageUrl: './images/poiTest/icons/Carlton Primary School.png', id: 'Carlton Primary School'},
    {imageUrl: './images/poiTest/icons/Carlton Gardens Primary School.png', id: 'Carlton Gardens Primary School'},
    {imageUrl: './images/poiTest/icons/Epworth Freemasons Hospital.png', id: 'Epworth Freemasons Hospital'},
    {imageUrl: './images/poiTest/icons/Epworth Freemasons Hospital : Medical Centre.png', id: 'Epworth Freemasons Hospital : Medical Centre'},
    {imageUrl: './images/poiTest/icons/Melbourne Private Hospital.png', id: 'Melbourne Private Hospital'},
    {imageUrl: './images/poiTest/icons/Melbourne International Shooting Club.png', id: 'Melbourne International Shooting Club'},
    {imageUrl: './images/poiTest/icons/Royal Park Golf Course.png', id: 'Royal Park Golf Course'},
    {imageUrl: './images/poiTest/icons/County Court Melbourne.png', id: 'County Court Melbourne'},
    {imageUrl: './images/poiTest/icons/Melbourne Childrens Court.png', id: 'Melbourne Childrens Court'},
    {imageUrl: './images/poiTest/icons/Conservatory.png', id: 'Conservatory'},
    {imageUrl: './images/poiTest/icons/Commonwealth Law Courts.png', id: 'Commonwealth Law Courts'},
    {imageUrl: './images/poiTest/icons/Shrine of Remembrance.png', id: 'Shrine of Remembrance'},
    {imageUrl: './images/poiTest/icons/NGV International.png', id: 'NGV International'},
    {imageUrl: './images/poiTest/icons/Melbourne Recital Centre.png', id: 'Melbourne Recital Centre'},
    {imageUrl: './images/poiTest/icons/Elisabeth Murdoch Hall.png', id: 'Elisabeth Murdoch Hall'},
    {imageUrl: './images/poiTest/icons/Sidney Myer Music Bowl.png', id: 'Sidney Myer Music Bowl'},
    {imageUrl: './images/poiTest/icons/Melbourne Town Hall.png', id: 'Melbourne Town Hall'},
    {imageUrl: './images/poiTest/icons/Supreme Court.png', id: 'Supreme Court'},
    {imageUrl: './images/poiTest/icons/State Library Victoria.png', id: 'State Library Victoria'},
    {imageUrl: './images/poiTest/icons/Royal Dental Hospital.png', id: 'Royal Dental Hospital'},
    {imageUrl: './images/poiTest/icons/Peter Maccallum Cancer Institute.png', id: 'Peter Maccallum Cancer Institute'},
    {imageUrl: './images/poiTest/icons/Royal Melbourne Hospital.png', id: 'Royal Melbourne Hospital'},
    {imageUrl: './images/poiTest/icons/Alfred Hospital.png', id: 'Alfred Hospital'},
    {imageUrl: './images/poiTest/icons/Royal Childrens Hospital.png', id: 'Royal Childrens Hospital'},
    {imageUrl: './images/poiTest/icons/Royal Womens Hospital.png', id: 'Royal Womens Hospital'},
    {imageUrl: './images/poiTest/icons/The Royal Victorian Eye & Ear Hospital.png', id: 'The Royal Victorian Eye & Ear Hospital'},
    {imageUrl: './images/poiTest/icons/North Melbourne Railway Station.png', id: 'North Melbourne Railway Station'},
    {imageUrl: './images/poiTest/icons/Melbourne Central Railway Station.png', id: 'Melbourne Central Railway Station'},
    {imageUrl: './images/poiTest/icons/Flinders Street Railway Station.png', id: 'Flinders Street Railway Station'},
    {imageUrl: './images/poiTest/icons/Newmarket Railway Station.png', id: 'Newmarket Railway Station'},
    {imageUrl: './images/poiTest/icons/Showgrounds Railway Station (Flemington).png', id: 'Showgrounds Railway Station (Flemington)'},
    {imageUrl: './images/poiTest/icons/Flemington Racecourse Railway Station.png', id: 'Flemington Racecourse Railway Station'},
    {imageUrl: './images/poiTest/icons/Flagstaff Railway Station.png', id: 'Flagstaff Railway Station'},
    {imageUrl: './images/poiTest/icons/Parliament Railway Station.png', id: 'Parliament Railway Station'},
    {imageUrl: './images/poiTest/icons/Royal Park Railway Station.png', id: 'Royal Park Railway Station'},
    {imageUrl: './images/poiTest/icons/South Kensington Railway Station.png', id: 'South Kensington Railway Station'},
    {imageUrl: './images/poiTest/icons/Kensington Railway Station.png', id: 'Kensington Railway Station'},
    {imageUrl: './images/poiTest/icons/Jolimont-MCG Railway Station (East Melbourne) - Train stop.png', id: 'Jolimont-MCG Railway Station (East Melbourne) - Train stop'},
    {imageUrl: './images/poiTest/icons/Richmond Railway Station (Richmond) - Train stop.png', id: 'Richmond Railway Station (Richmond) - Train stop'},
    {imageUrl: './images/poiTest/icons/Southern Cross Railway Station.png', id: 'Southern Cross Railway Station'},
    {imageUrl: './images/poiTest/icons/Flemington Bridge Railway Station.png', id: 'Flemington Bridge Railway Station'},
    {imageUrl: './images/poiTest/icons/Queen Victoria Market.png', id: 'Queen Victoria Market'},
    {imageUrl: './images/poiTest/icons/Treasury Reserve.png', id: 'Treasury Reserve'},
    {imageUrl: './images/poiTest/icons/ANZ \'Gothic\' Bank.png', id: 'ANZ \'Gothic\' Bank'},
    {imageUrl: './images/poiTest/icons/Melbourne Central.png', id: 'Melbourne Central'},
    {imageUrl: './images/poiTest/icons/Southgate Arts and Leisure Precinct.png', id: 'Southgate Arts and Leisure Precinct'},
    {imageUrl: './images/poiTest/icons/Council House 2 (CH2).png', id: 'Council House 2 (CH2)'},
    {imageUrl: './images/poiTest/icons/Freshwater Place.png', id: 'Freshwater Place'},
    {imageUrl: './images/poiTest/icons/QV Village.png', id: 'QV Village'},
    {imageUrl: './images/poiTest/icons/Eureka Tower.png', id: 'Eureka Tower'},
    {imageUrl: './images/poiTest/icons/Melbourne Girls Grammar School.png', id: 'Melbourne Girls Grammar School'},
    {imageUrl: './images/poiTest/icons/Wesley College.png', id: 'Wesley College'},
    {imageUrl: './images/poiTest/icons/University High School.png', id: 'University High School'},
    {imageUrl: './images/poiTest/icons/Melbourne Grammar School.png', id: 'Melbourne Grammar School'},
    {imageUrl: './images/poiTest/icons/Melbourne Wholesale Fish Market.png', id: 'Melbourne Wholesale Fish Market'},
    {imageUrl: './images/poiTest/icons/East Melbourne Synagogue.png', id: 'East Melbourne Synagogue'},
    {imageUrl: './images/poiTest/icons/RMIT University.png', id: 'RMIT University'},
    {imageUrl: './images/poiTest/icons/University of Melbourne.png', id: 'University of Melbourne'},
    {imageUrl: './images/poiTest/icons/BIO 21 Institute.png', id: 'BIO 21 Institute'},
    {imageUrl: './images/poiTest/icons/University of Melbourne (VCA and Music).png', id: 'University of Melbourne (VCA and Music)'},
    {imageUrl: './images/poiTest/icons/La Mama Theatre.png', id: 'La Mama Theatre'},
    {imageUrl: './images/poiTest/icons/Comedy Theatre.png', id: 'Comedy Theatre'},
    {imageUrl: './images/poiTest/icons/Her Majesty\'s Theatre.png', id: 'Her Majesty\'s Theatre'},
    {imageUrl: './images/poiTest/icons/Carlton Courthouse Theatre.png', id: 'Carlton Courthouse Theatre'},
    {imageUrl: './images/poiTest/icons/Athanaeum Theatre.png', id: 'Athanaeum Theatre'},
    {imageUrl: './images/poiTest/icons/Hamer Hall.png', id: 'Hamer Hall'},
    {imageUrl: './images/poiTest/icons/MTC Theatre.png', id: 'MTC Theatre'},
    {imageUrl: './images/poiTest/icons/Malthouse Theatre.png', id: 'Malthouse Theatre'},
    {imageUrl: './images/poiTest/icons/Regent Theatre.png', id: 'Regent Theatre'},
    {imageUrl: './images/poiTest/icons/Princess Theatre.png', id: 'Princess Theatre'},
    {imageUrl: './images/poiTest/icons/St Martins Youth Arts Centre.png', id: 'St Martins Youth Arts Centre'},
    {imageUrl: './images/poiTest/icons/State Theatre.png', id: 'State Theatre'},
    {imageUrl: './images/poiTest/icons/Playhouse.png', id: 'Playhouse'},
    {imageUrl: './images/poiTest/icons/FairFax Studio.png', id: 'FairFax Studio'},
    {imageUrl: './images/poiTest/icons/Port of Melbourne.png', id: 'Port of Melbourne'},
    {imageUrl: './images/poiTest/icons/Melbourne International Karting Complex.png', id: 'Melbourne International Karting Complex'},
    {imageUrl: './images/poiTest/icons/Melbourne Visitor Centre.png', id: 'Melbourne Visitor Centre'},
    {imageUrl: './images/poiTest/icons/Melbourne Visitor Booth.png', id: 'Melbourne Visitor Booth'},
]