imagesAll = [
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/mapicon/museum.png', id: 'museum'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/mapicon/church.png\n', id: 'church'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/mapicon/shop.png', id: 'shop'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/mapicon/nature.png', id: 'nature'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/mapicon/theatre.png', id: 'theatre'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/mapicon/harbor.png', id: 'harbor'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/mapicon/indoor.png', id: 'indoor'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/mapicon/building.png', id: 'building'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/mapicon/sport.png', id: 'sport'},
    {imageUrl: './images/mapicon/tram.png', id: 'railwayStation'},


    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Melbourne%20Aquarium.png', id: 'Melbourne Aquarium'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/The%20Museum%20Of%20Australian%20Chinese%20History.png', id: 'The Museum Of Australian Chinese History'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Australian%20Centre%20For%20The%20Moving%20Image%20(ACMI).png', id: 'Australian Centre For The Moving Image (ACMI)'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Cooks\'%20Cottage.png', id: 'Cooks\' Cottage'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Koorie%20Heritage%20Trust%20Inc.png', id: 'Koorie Heritage Trust Inc'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/The%20Ian%20Potter%20Museum%20Of%20Art.png', id: 'The Ian Potter Museum Of Art'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Fire%20Services%20Museum%20Victoria.png', id: 'Fire Services Museum Victoria'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Immigration%20Museum.png', id: 'Immigration Museum'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Victoria%20Police%20Museum.png', id: 'Victoria Police Museum'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Sinclair\'s%20Cottage.png', id: 'Sinclair\'s Cottage'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/National%20Sports%20Museum.png', id: 'National Sports Museum'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Melbourne%20Museum.png', id: 'Melbourne Museum'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Fox%20Classic%20Car%20Collection.png', id: 'Fox Classic Car Collection'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Thoroughbred%20Racing%20Gallery.png', id: 'Thoroughbred Racing Gallery'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/The%20Ian%20Potter%20Centre:%20NGV%20Australia.png', id: 'The Ian Potter Centre: NGV Australia'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Victorian%20Arts%20Centre.png', id: 'Victorian Arts Centre'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Australian%20Centre%20for%20Contemporary%20Art.png', id: 'Australian Centre for Contemporary Art'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Polly%20Woodside.png', id: 'Polly Woodside'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Old%20Melbourne%20Gaol%20Crime%20&%20Justice%20Experience.png', id: 'Old Melbourne Gaol Crime & Justice Experience'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Webb%20Bridge.png', id: 'Webb Bridge'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Crown%20Entertainment%20Complex.png', id: 'Crown Entertainment Complex'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Melbourne%20General%20Cemetery.png', id: 'Melbourne General Cemetery'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/St%20Pauls%20Cathedral.png', id: 'St Pauls Cathedral'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/St%20Patricks%20Cathedral.png', id: 'St Patricks Cathedral'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/The%20Parish%20of%20Christ%20Church%20South%20Yarra.png', id: 'The Parish of Christ Church South Yarra'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/South%20Yarra%20Presbyterian%20Church.png', id: 'South Yarra Presbyterian Church'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/St%20Thomas%20Aquinas%20Church.png', id: 'St Thomas Aquinas Church'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Collins%20Street%20Baptist%20Church.png', id: 'Collins Street Baptist Church'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Holy%20Rosary.png', id: 'Holy Rosary'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Christ%20Church%20Kensington.png', id: 'Christ Church Kensington'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/St%20Alban%20Anglican%20Church.png', id: 'St Alban Anglican Church'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Ukranian%20Catholic%20Cathedral.png', id: 'Ukranian Catholic Cathedral'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/St%20Michaels.png', id: 'St Michaels'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Our%20Lady%20of%20Lebanon%20Church.png', id: 'Our Lady of Lebanon Church'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/All%20Nations%20Uniting%20Church.png', id: 'All Nations Uniting Church'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Melbourne%20Unitarian%20Church.png', id: 'Melbourne Unitarian Church'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/North%20Melbourne%20Uniting.png', id: 'North Melbourne Uniting'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/St%20Johns%20Lutheran%20Church.png', id: 'St Johns Lutheran Church'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Holy%20Trinity.png', id: 'Holy Trinity'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Lutheran%20Trinity%20Church.png', id: 'Lutheran Trinity Church'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/St%20Peter\'s%20Eastern%20Hill.png', id: 'St Peter\'s Eastern Hill'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Greek%20Orthodox%20Church.png', id: 'Greek Orthodox Church'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/St%20Michael\'s%20Uniting%20Church.png', id: 'St Michael\'s Uniting Church'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Scots%20Church.png', id: 'Scots Church'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Church%20of%20Christ.png', id: 'Church of Christ'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Welsh%20Presbyterian%20Church.png', id: 'Welsh Presbyterian Church'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Romanian%20Orthodox.png', id: 'Romanian Orthodox'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/St%20Mary\'s%20Anglican%20Church.png', id: 'St Mary\'s Anglican Church'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/St%20James%20Church.png', id: 'St James Church'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/St%20Augustines%20Church.png', id: 'St Augustines Church'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Wesley%20Church.png', id: 'Wesley Church'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/St%20Francis%20Church.png', id: 'St Francis Church'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/IMAX%20Melbourne.png', id: 'IMAX Melbourne'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Harbour%20Town.png', id: 'Harbour Town'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Railway%20Good%20Shed%20No%202.png', id: 'Railway Good Shed No 2'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/David%20Jones.png', id: 'David Jones'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Myer.png', id: 'Myer'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Bishopscourt.png', id: 'Bishopscourt'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Government%20House.png', id: 'Government House'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Channel%207%20-%20Melbourne%20Broadcast%20Centre.png', id: 'Channel 7 - Melbourne Broadcast Centre'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Central%20City%20Studios.png', id: 'Central City Studios'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Metropolitan%20Fire%20Brigade%20(MFB).png', id: 'Metropolitan Fire Brigade (MFB)'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Dallas%20Brooks%20Centre.png', id: 'Dallas Brooks Centre'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Central%20Pier.png', id: 'Central Pier'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Melbourne%20Convention%20Centre.png', id: 'Melbourne Convention Centre'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Melbourne%20Exhibition%20Centre.png', id: 'Melbourne Exhibition Centre'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Kangan%20Batman%20Tafe.png', id: 'Kangan Batman Tafe'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Melbourne%20Magistrates%20Court.png', id: 'Melbourne Magistrates Court'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/North%20Melbourne%20Recreation%20Centre%20(Gymnasium).png', id: 'North Melbourne Recreation Centre (Gymnasium)'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/The%20Mission%20To%20Seafarers%20Victoria.png', id: 'The Mission To Seafarers Victoria'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Carlton%20Baths.png', id: 'Carlton Baths'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Icehouse.png', id: 'Icehouse'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Artplay.png', id: 'Artplay'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Kraft.png', id: 'Kraft'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Lincoln%20Square.png', id: 'Lincoln Square'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Sandridge%20Rail%20Bridge.png', id: 'Sandridge Rail Bridge'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Westgate%20Park.png', id: 'Westgate Park'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Murchinson%20Square.png', id: 'Murchinson Square'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Macarthur%20Square.png', id: 'Macarthur Square'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Piazza%20Italia.png', id: 'Piazza Italia'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Argyle%20Square.png', id: 'Argyle Square'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Fitzroy%20Gardens.png', id: 'Fitzroy Gardens'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Fawkner%20Park.png', id: 'Fawkner Park'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Flagstaff%20Gardens.png', id: 'Flagstaff Gardens'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Royal%20Botanic%20Gardens.png', id: 'Royal Botanic Gardens'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Shrine%20of%20Rembrance%20Reserve.png', id: 'Shrine of Rembrance Reserve'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Princes%20Park.png', id: 'Princes Park'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Royal%20Park.png', id: 'Royal Park'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/J.J%20Holland%20Park.png', id: 'J.J Holland Park'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/North%20Melbourne%20Recreation%20Reserve.png', id: 'North Melbourne Recreation Reserve'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Alexandra%20Gardens.png', id: 'Alexandra Gardens'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Riverslide%20Skate%20Park.png', id: 'Riverslide Skate Park'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Newmarket%20Reserve.png', id: 'Newmarket Reserve'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Point%20Park.png', id: 'Point Park'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Docklands%20Park.png', id: 'Docklands Park'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/New%20Quay.png', id: 'New Quay'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Federation%20Square.png', id: 'Federation Square'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Queen%20Victoria%20Gardens.png', id: 'Queen Victoria Gardens'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Richmond%20Football%20Club.png', id: 'Richmond Football Club'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Batman%20Park.png', id: 'Batman Park'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Treasury%20Gardens.png', id: 'Treasury Gardens'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Kings%20Domain.png', id: 'Kings Domain'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Carlton%20Gardens%20North.png', id: 'Carlton Gardens North'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Powlett%20Reserve.png', id: 'Powlett Reserve'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Carlton%20Gardens%20South.png', id: 'Carlton Gardens South'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/The%20Melbourne%20Athenaeum%20Library.png', id: 'The Melbourne Athenaeum Library'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Etihad%20Stadium.png', id: 'Etihad Stadium'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Westpac%20Centre.png', id: 'Westpac Centre'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/City%20Baths.png', id: 'City Baths'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/North%20Melbourne%20Recreation%20Centre%20(Aquatic).png', id: 'North Melbourne Recreation Centre (Aquatic)'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Margaret%20Court%20Arena.png', id: 'Margaret Court Arena'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Melbourne%20Park.png', id: 'Melbourne Park'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Rod%20Laver%20Arena.png', id: 'Rod Laver Arena'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/AAMI%20Park.png', id: 'AAMI Park'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Melbourne%20Cricket%20Ground%20(MCG).png', id: 'Melbourne Cricket Ground (MCG)'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Flemington%20Racecourse.png', id: 'Flemington Racecourse'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Visy%20Park.png', id: 'Visy Park'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Carlton%20Football%20Club.png', id: 'Carlton Football Club'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/State%20Netball%20Hockey%20Centre.png', id: 'State Netball Hockey Centre'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/New%20Quay%20Marina.png', id: 'New Quay Marina'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Eureka%20Skydeck%2088.png', id: 'Eureka Skydeck 88'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Melbourne%20Star%20Observation%20Wheel.png', id: 'Melbourne Star Observation Wheel'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/State%20Coroners%20Office.png', id: 'State Coroners Office'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Donor%20Tissue%20Bank%20of%20Victoria.png', id: 'Donor Tissue Bank of Victoria'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Victorian%20Insitute%20of%20Forensic%20Medicine.png', id: 'Victorian Insitute of Forensic Medicine'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Coronial%20Services%20Centre%20of%20Victoria.png', id: 'Coronial Services Centre of Victoria'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/SBS%20(Special%20Broadcasting%20Service).png', id: 'SBS (Special Broadcasting Service)'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Former%20Royal%20Mint.png', id: 'Former Royal Mint'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Parliament%20House.png', id: 'Parliament House'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Australian%20Red%20Cross.png', id: 'Australian Red Cross'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Old%20Treasury%20Building.png', id: 'Old Treasury Building'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Melbourne%20Showgrounds.png', id: 'Melbourne Showgrounds'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Riverside%20Park.png', id: 'Riverside Park'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Wonderland%20Park.png', id: 'Wonderland Park'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Melbourne%20Zoo.png', id: 'Melbourne Zoo'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Victoria%20Police.png', id: 'Victoria Police'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/North%20Melbourne%20Primary%20School.png', id: 'North Melbourne Primary School'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Kensington%20Primary%20School.png', id: 'Kensington Primary School'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Carlton%20Primary%20School.png', id: 'Carlton Primary School'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Carlton%20Gardens%20Primary%20School.png', id: 'Carlton Gardens Primary School'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Epworth%20Freemasons%20Hospital.png', id: 'Epworth Freemasons Hospital'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Epworth%20Freemasons%20Hospital%20:%20Medical%20Centre.png', id: 'Epworth Freemasons Hospital : Medical Centre'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Melbourne%20Private%20Hospital.png', id: 'Melbourne Private Hospital'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Melbourne%20International%20Shooting%20Club.png', id: 'Melbourne International Shooting Club'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Royal%20Park%20Golf%20Course.png', id: 'Royal Park Golf Course'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/County%20Court%20Melbourne.png', id: 'County Court Melbourne'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Melbourne%20Childrens%20Court.png', id: 'Melbourne Childrens Court'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Conservatory.png', id: 'Conservatory'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Commonwealth%20Law%20Courts.png', id: 'Commonwealth Law Courts'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Shrine%20of%20Remembrance.png', id: 'Shrine of Remembrance'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/NGV%20International.png', id: 'NGV International'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Melbourne%20Recital%20Centre.png', id: 'Melbourne Recital Centre'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Elisabeth%20Murdoch%20Hall.png', id: 'Elisabeth Murdoch Hall'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Sidney%20Myer%20Music%20Bowl.png', id: 'Sidney Myer Music Bowl'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Melbourne%20Town%20Hall.png', id: 'Melbourne Town Hall'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Supreme%20Court.png', id: 'Supreme Court'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/State%20Library%20Victoria.png', id: 'State Library Victoria'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Royal%20Dental%20Hospital.png', id: 'Royal Dental Hospital'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Peter%20Maccallum%20Cancer%20Institute.png', id: 'Peter Maccallum Cancer Institute'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Royal%20Melbourne%20Hospital.png', id: 'Royal Melbourne Hospital'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Alfred%20Hospital.png', id: 'Alfred Hospital'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Royal%20Childrens%20Hospital.png', id: 'Royal Childrens Hospital'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Royal%20Womens%20Hospital.png', id: 'Royal Womens Hospital'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/The%20Royal%20Victorian%20Eye%20&%20Ear%20Hospital.png', id: 'The Royal Victorian Eye & Ear Hospital'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/North%20Melbourne%20Railway%20Station.png', id: 'North Melbourne Railway Station'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Melbourne%20Central%20Railway%20Station.png', id: 'Melbourne Central Railway Station'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Flinders%20Street%20Railway%20Station.png', id: 'Flinders Street Railway Station'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Newmarket%20Railway%20Station.png', id: 'Newmarket Railway Station'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Showgrounds%20Railway%20Station%20(Flemington).png', id: 'Showgrounds Railway Station (Flemington)'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Flemington%20Racecourse%20Railway%20Station.png', id: 'Flemington Racecourse Railway Station'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Flagstaff%20Railway%20Station.png', id: 'Flagstaff Railway Station'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Parliament%20Railway%20Station.png', id: 'Parliament Railway Station'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Royal%20Park%20Railway%20Station.png', id: 'Royal Park Railway Station'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/South%20Kensington%20Railway%20Station.png', id: 'South Kensington Railway Station'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Kensington%20Railway%20Station.png', id: 'Kensington Railway Station'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Jolimont-MCG%20Railway%20Station%20(East%20Melbourne)%20-%20Train%20stop.png', id: 'Jolimont-MCG Railway Station (East Melbourne) - Train stop'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Richmond%20Railway%20Station%20(Richmond)%20-%20Train%20stop.png', id: 'Richmond Railway Station (Richmond) - Train stop'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Southern%20Cross%20Railway%20Station.png', id: 'Southern Cross Railway Station'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Flemington%20Bridge%20Railway%20Station.png', id: 'Flemington Bridge Railway Station'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Queen%20Victoria%20Market.png', id: 'Queen Victoria Market'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Treasury%20Reserve.png', id: 'Treasury Reserve'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/ANZ%20\'Gothic\'%20Bank.png', id: 'ANZ \'Gothic\' Bank'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Melbourne%20Central.png', id: 'Melbourne Central'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Southgate%20Arts%20and%20Leisure%20Precinct.png', id: 'Southgate Arts and Leisure Precinct'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Council%20House%202%20(CH2).png', id: 'Council House 2 (CH2)'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Freshwater%20Place.png', id: 'Freshwater Place'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/QV%20Village.png', id: 'QV Village'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Eureka%20Tower.png', id: 'Eureka Tower'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Melbourne%20Girls%20Grammar%20School.png', id: 'Melbourne Girls Grammar School'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Wesley%20College.png', id: 'Wesley College'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/University%20High%20School.png', id: 'University High School'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Melbourne%20Grammar%20School.png', id: 'Melbourne Grammar School'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Melbourne%20Wholesale%20Fish%20Market.png', id: 'Melbourne Wholesale Fish Market'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/East%20Melbourne%20Synagogue.png', id: 'East Melbourne Synagogue'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/RMIT%20University.png', id: 'RMIT University'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/University%20of%20Melbourne.png', id: 'University of Melbourne'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/BIO%2021%20Institute.png', id: 'BIO 21 Institute'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/University%20of%20Melbourne%20(VCA%20and%20Music).png', id: 'University of Melbourne (VCA and Music)'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/La%20Mama%20Theatre.png', id: 'La Mama Theatre'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Comedy%20Theatre.png', id: 'Comedy Theatre'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Her%20Majesty\'s%20Theatre.png', id: 'Her Majesty\'s Theatre'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Carlton%20Courthouse%20Theatre.png', id: 'Carlton Courthouse Theatre'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Athanaeum%20Theatre.png', id: 'Athanaeum Theatre'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Hamer%20Hall.png', id: 'Hamer Hall'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/MTC%20Theatre.png', id: 'MTC Theatre'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Malthouse%20Theatre.png', id: 'Malthouse Theatre'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Regent%20Theatre.png', id: 'Regent Theatre'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Princess%20Theatre.png', id: 'Princess Theatre'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/St%20Martins%20Youth%20Arts%20Centre.png', id: 'St Martins Youth Arts Centre'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/State%20Theatre.png', id: 'State Theatre'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Playhouse.png', id: 'Playhouse'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/FairFax%20Studio.png', id: 'FairFax Studio'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Port%20of%20Melbourne.png', id: 'Port of Melbourne'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Melbourne%20International%20Karting%20Complex.png', id: 'Melbourne International Karting Complex'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Melbourne%20Visitor%20Centre.png', id: 'Melbourne Visitor Centre'},
    {imageUrl: 'https://ivassignment.oss-ap-southeast-2.aliyuncs.com/images/poi/poiicons/Melbourne%20Visitor%20Booth.png', id: 'Melbourne Visitor Booth'},
]