stopsAll = [
    ['Melbourne Aquarium', 'Melbourne Aquarium'],
    ['The Museum Of Australian Chinese History', 'The Museum Of Australian Chinese History'],
    ['Australian Centre For The Moving Image (ACMI)', 'Australian Centre For The Moving Image (ACMI)'],
    ['Cooks\' Cottage', 'Cooks\' Cottage'],
    ['Koorie Heritage Trust Inc', 'Koorie Heritage Trust Inc'],
    ['The Ian Potter Museum Of Art', 'The Ian Potter Museum Of Art'],
    ['Fire Services Museum Victoria', 'Fire Services Museum Victoria'],
    ['Immigration Museum', 'Immigration Museum'],
    ['Victoria Police Museum', 'Victoria Police Museum'],
    ['Sinclair\'s Cottage', 'Sinclair\'s Cottage'],
    ['National Sports Museum', 'National Sports Museum'],
    ['Melbourne Museum', 'Melbourne Museum'],
    ['Fox Classic Car Collection', 'Fox Classic Car Collection'],
    ['Thoroughbred Racing Gallery', 'Thoroughbred Racing Gallery'],
    ['The Ian Potter Centre: NGV Australia', 'The Ian Potter Centre: NGV Australia'],
    ['Victorian Arts Centre', 'Victorian Arts Centre'],
    ['Australian Centre for Contemporary Art', 'Australian Centre for Contemporary Art'],
    ['Polly Woodside', 'Polly Woodside'],
    ['Old Melbourne Gaol Crime & Justice Experience', 'Old Melbourne Gaol Crime & Justice Experience'],
    ['Webb Bridge', 'Webb Bridge'],
    ['Crown Entertainment Complex', 'Crown Entertainment Complex'],
    ['Melbourne General Cemetery', 'Melbourne General Cemetery'],
    ['St Pauls Cathedral', 'St Pauls Cathedral'],
    ['St Patricks Cathedral', 'St Patricks Cathedral'],
    ['The Parish of Christ Church South Yarra', 'The Parish of Christ Church South Yarra'],
    ['South Yarra Presbyterian Church', 'South Yarra Presbyterian Church'],
    ['St Thomas Aquinas Church', 'St Thomas Aquinas Church'],
    ['Collins Street Baptist Church', 'Collins Street Baptist Church'],
    ['Holy Rosary', 'Holy Rosary'],
    ['Christ Church Kensington', 'Christ Church Kensington'],
    ['St Alban Anglican Church', 'St Alban Anglican Church'],
    ['Ukranian Catholic Cathedral', 'Ukranian Catholic Cathedral'],
    ['St Michaels', 'St Michaels'],
    ['Our Lady of Lebanon Church', 'Our Lady of Lebanon Church'],
    ['All Nations Uniting Church', 'All Nations Uniting Church'],
    ['Melbourne Unitarian Church', 'Melbourne Unitarian Church'],
    ['North Melbourne Uniting', 'North Melbourne Uniting'],
    ['St Johns Lutheran Church', 'St Johns Lutheran Church'],
    ['Holy Trinity', 'Holy Trinity'],
    ['Lutheran Trinity Church', 'Lutheran Trinity Church'],
    ['St Peter\'s Eastern Hill', 'St Peter\'s Eastern Hill'],
    ['Greek Orthodox Church', 'Greek Orthodox Church'],
    ['St Michael\'s Uniting Church', 'St Michael\'s Uniting Church'],
    ['Scots Church', 'Scots Church'],
    ['Church of Christ', 'Church of Christ'],
    ['Welsh Presbyterian Church', 'Welsh Presbyterian Church'],
    ['Romanian Orthodox', 'Romanian Orthodox'],
    ['St Mary\'s Anglican Church', 'St Mary\'s Anglican Church'],
    ['St James Church', 'St James Church'],
    ['St Augustines Church', 'St Augustines Church'],
    ['Wesley Church', 'Wesley Church'],
    ['St Francis Church', 'St Francis Church'],
    ['IMAX Melbourne', 'IMAX Melbourne'],
    ['Harbour Town', 'Harbour Town'],
    ['Railway Good Shed No 2', 'Railway Good Shed No 2'],
    ['David Jones', 'David Jones'],
    ['Myer', 'Myer'],
    ['Bishopscourt', 'Bishopscourt'],
    ['Government House', 'Government House'],
    ['Channel 7 - Melbourne Broadcast Centre', 'Channel 7 - Melbourne Broadcast Centre'],
    ['Central City Studios', 'Central City Studios'],
    ['Metropolitan Fire Brigade (MFB)', 'Metropolitan Fire Brigade (MFB)'],
    ['Dallas Brooks Centre', 'Dallas Brooks Centre'],
    ['Central Pier', 'Central Pier'],
    ['Melbourne Convention Centre', 'Melbourne Convention Centre'],
    ['Melbourne Exhibition Centre', 'Melbourne Exhibition Centre'],
    ['Kangan Batman Tafe', 'Kangan Batman Tafe'],
    ['Melbourne Magistrates Court', 'Melbourne Magistrates Court'],
    ['North Melbourne Recreation Centre (Gymnasium)', 'North Melbourne Recreation Centre (Gymnasium)'],
    ['The Mission To Seafarers Victoria', 'The Mission To Seafarers Victoria'],
    ['Carlton Baths', 'Carlton Baths'],
    ['Icehouse', 'Icehouse'],
    ['Artplay', 'Artplay'],
    ['Kraft', 'Kraft'],
    ['Lincoln Square', 'Lincoln Square'],
    ['Sandridge Rail Bridge', 'Sandridge Rail Bridge'],
    ['Westgate Park', 'Westgate Park'],
    ['Murchinson Square', 'Murchinson Square'],
    ['Macarthur Square', 'Macarthur Square'],
    ['Piazza Italia', 'Piazza Italia'],
    ['Argyle Square', 'Argyle Square'],
    ['Fitzroy Gardens', 'Fitzroy Gardens'],
    ['Fawkner Park', 'Fawkner Park'],
    ['Flagstaff Gardens', 'Flagstaff Gardens'],
    ['Royal Botanic Gardens', 'Royal Botanic Gardens'],
    ['Shrine of Rembrance Reserve', 'Shrine of Rembrance Reserve'],
    ['Princes Park', 'Princes Park'],
    ['Royal Park', 'Royal Park'],
    ['J.J Holland Park', 'J.J Holland Park'],
    ['North Melbourne Recreation Reserve', 'North Melbourne Recreation Reserve'],
    ['Alexandra Gardens', 'Alexandra Gardens'],
    ['Riverslide Skate Park', 'Riverslide Skate Park'],
    ['Newmarket Reserve', 'Newmarket Reserve'],
    ['Point Park', 'Point Park'],
    ['Docklands Park', 'Docklands Park'],
    ['New Quay', 'New Quay'],
    ['Federation Square', 'Federation Square'],
    ['Queen Victoria Gardens', 'Queen Victoria Gardens'],
    ['Richmond Football Club', 'Richmond Football Club'],
    ['Batman Park', 'Batman Park'],
    ['Treasury Gardens', 'Treasury Gardens'],
    ['Kings Domain', 'Kings Domain'],
    ['Carlton Gardens North', 'Carlton Gardens North'],
    ['Powlett Reserve', 'Powlett Reserve'],
    ['Carlton Gardens South', 'Carlton Gardens South'],
    ['The Melbourne Athenaeum Library', 'The Melbourne Athenaeum Library'],
    ['Etihad Stadium', 'Etihad Stadium'],
    ['Westpac Centre', 'Westpac Centre'],
    ['City Baths', 'City Baths'],
    ['North Melbourne Recreation Centre (Aquatic)', 'North Melbourne Recreation Centre (Aquatic)'],
    ['Margaret Court Arena', 'Margaret Court Arena'],
    ['Melbourne Park', 'Melbourne Park'],
    ['Rod Laver Arena', 'Rod Laver Arena'],
    ['AAMI Park', 'AAMI Park'],
    ['Melbourne Cricket Ground (MCG)', 'Melbourne Cricket Ground (MCG)'],
    ['Flemington Racecourse', 'Flemington Racecourse'],
    ['Visy Park', 'Visy Park'],
    ['Carlton Football Club', 'Carlton Football Club'],
    ['State Netball Hockey Centre', 'State Netball Hockey Centre'],
    ['New Quay Marina', 'New Quay Marina'],
    ['Eureka Skydeck 88', 'Eureka Skydeck 88'],
    ['Melbourne Star Observation Wheel', 'Melbourne Star Observation Wheel'],
    ['State Coroners Office', 'State Coroners Office'],
    ['Donor Tissue Bank of Victoria', 'Donor Tissue Bank of Victoria'],
    ['Victorian Insitute of Forensic Medicine', 'Victorian Insitute of Forensic Medicine'],
    ['Coronial Services Centre of Victoria', 'Coronial Services Centre of Victoria'],
    ['SBS (Special Broadcasting Service)', 'SBS (Special Broadcasting Service)'],
    ['Former Royal Mint', 'Former Royal Mint'],
    ['Parliament House', 'Parliament House'],
    ['Australian Red Cross', 'Australian Red Cross'],
    ['Old Treasury Building', 'Old Treasury Building'],
    ['Melbourne Showgrounds', 'Melbourne Showgrounds'],
    ['Riverside Park', 'Riverside Park'],
    ['Wonderland Park', 'Wonderland Park'],
    ['Melbourne Zoo', 'Melbourne Zoo'],
    ['Victoria Police', 'Victoria Police'],
    ['North Melbourne Primary School', 'North Melbourne Primary School'],
    ['Kensington Primary School', 'Kensington Primary School'],
    ['Carlton Primary School', 'Carlton Primary School'],
    ['Carlton Gardens Primary School', 'Carlton Gardens Primary School'],
    ['Epworth Freemasons Hospital', 'Epworth Freemasons Hospital'],
    ['Epworth Freemasons Hospital : Medical Centre', 'Epworth Freemasons Hospital : Medical Centre'],
    ['Melbourne Private Hospital', 'Melbourne Private Hospital'],
    ['Melbourne International Shooting Club', 'Melbourne International Shooting Club'],
    ['Royal Park Golf Course', 'Royal Park Golf Course'],
    ['County Court Melbourne', 'County Court Melbourne'],
    ['Melbourne Childrens Court', 'Melbourne Childrens Court'],
    ['Conservatory', 'Conservatory'],
    ['Commonwealth Law Courts', 'Commonwealth Law Courts'],
    ['Shrine of Remembrance', 'Shrine of Remembrance'],
    ['NGV International', 'NGV International'],
    ['Melbourne Recital Centre', 'Melbourne Recital Centre'],
    ['Elisabeth Murdoch Hall', 'Elisabeth Murdoch Hall'],
    ['Sidney Myer Music Bowl', 'Sidney Myer Music Bowl'],
    ['Melbourne Town Hall', 'Melbourne Town Hall'],
    ['Supreme Court', 'Supreme Court'],
    ['State Library Victoria', 'State Library Victoria'],
    ['Royal Dental Hospital', 'Royal Dental Hospital'],
    ['Peter Maccallum Cancer Institute', 'Peter Maccallum Cancer Institute'],
    ['Royal Melbourne Hospital', 'Royal Melbourne Hospital'],
    ['Alfred Hospital', 'Alfred Hospital'],
    ['Royal Childrens Hospital', 'Royal Childrens Hospital'],
    ['Royal Womens Hospital', 'Royal Womens Hospital'],
    ['The Royal Victorian Eye & Ear Hospital', 'The Royal Victorian Eye & Ear Hospital'],
    ['North Melbourne Railway Station', 'North Melbourne Railway Station'],
    ['Melbourne Central Railway Station', 'Melbourne Central Railway Station'],
    ['Flinders Street Railway Station', 'Flinders Street Railway Station'],
    ['Newmarket Railway Station', 'Newmarket Railway Station'],
    ['Showgrounds Railway Station (Flemington)', 'Showgrounds Railway Station (Flemington)'],
    ['Flemington Racecourse Railway Station', 'Flemington Racecourse Railway Station'],
    ['Flagstaff Railway Station', 'Flagstaff Railway Station'],
    ['Parliament Railway Station', 'Parliament Railway Station'],
    ['Royal Park Railway Station', 'Royal Park Railway Station'],
    ['South Kensington Railway Station', 'South Kensington Railway Station'],
    ['Kensington Railway Station', 'Kensington Railway Station'],
    ['Jolimont-MCG Railway Station (East Melbourne) - Train stop', 'Jolimont-MCG Railway Station (East Melbourne) - Train stop'],
    ['Richmond Railway Station (Richmond) - Train stop', 'Richmond Railway Station (Richmond) - Train stop'],
    ['Southern Cross Railway Station', 'Southern Cross Railway Station'],
    ['Flemington Bridge Railway Station', 'Flemington Bridge Railway Station'],
    ['Queen Victoria Market', 'Queen Victoria Market'],
    ['Treasury Reserve', 'Treasury Reserve'],
    ['ANZ \'Gothic\' Bank', 'ANZ \'Gothic\' Bank'],
    ['Melbourne Central', 'Melbourne Central'],
    ['Southgate Arts and Leisure Precinct', 'Southgate Arts and Leisure Precinct'],
    ['Council House 2 (CH2)', 'Council House 2 (CH2)'],
    ['Freshwater Place', 'Freshwater Place'],
    ['QV Village', 'QV Village'],
    ['Eureka Tower', 'Eureka Tower'],
    ['Melbourne Girls Grammar School', 'Melbourne Girls Grammar School'],
    ['Wesley College', 'Wesley College'],
    ['University High School', 'University High School'],
    ['Melbourne Grammar School', 'Melbourne Grammar School'],
    ['Melbourne Wholesale Fish Market', 'Melbourne Wholesale Fish Market'],
    ['East Melbourne Synagogue', 'East Melbourne Synagogue'],
    ['RMIT University', 'RMIT University'],
    ['University of Melbourne', 'University of Melbourne'],
    ['BIO 21 Institute', 'BIO 21 Institute'],
    ['University of Melbourne (VCA and Music)', 'University of Melbourne (VCA and Music)'],
    ['La Mama Theatre', 'La Mama Theatre'],
    ['Comedy Theatre', 'Comedy Theatre'],
    ['Her Majesty\'s Theatre', 'Her Majesty\'s Theatre'],
    ['Carlton Courthouse Theatre', 'Carlton Courthouse Theatre'],
    ['Athanaeum Theatre', 'Athanaeum Theatre'],
    ['Hamer Hall', 'Hamer Hall'],
    ['MTC Theatre', 'MTC Theatre'],
    ['Malthouse Theatre', 'Malthouse Theatre'],
    ['Regent Theatre', 'Regent Theatre'],
    ['Princess Theatre', 'Princess Theatre'],
    ['St Martins Youth Arts Centre', 'St Martins Youth Arts Centre'],
    ['State Theatre', 'State Theatre'],
    ['Playhouse', 'Playhouse'],
    ['FairFax Studio', 'FairFax Studio'],
    ['Port of Melbourne', 'Port of Melbourne'],
    ['Melbourne International Karting Complex', 'Melbourne International Karting Complex'],
    ['Melbourne Visitor Centre', 'Melbourne Visitor Centre'],
    ['Melbourne Visitor Booth', 'Melbourne Visitor Booth'],
]